apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::751441960608:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::751441960608:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-D4DHLBZZIDM6
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-04T00:37:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1432"
  uid: 8574b3e9-b41e-49c6-8a30-63fd1afb42dc
